name: Deploy to Firebase Hosting on merge
'on': 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
# Run multiple commands using the runners shell
    steps:
      - uses: actions/checkout@v2
      - name: nav
        run: cd ./FrontendABCjobs
      - name: Install Dependencies
        run: |
          sudo npm i
          sudo npm i -g firebase-tools
      - name: Run Tests
        run: npm run test
      - name: Build Prod App
        run: |
          npm run build --if-present
      - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: project_id
